// import {
//   Geist,
//   Geist_Mono,
//   Playfair_Display,
//   Libre_Baskerville,
// } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// const playfair = Playfair_Display({
//   variable: "--font-playfair",
//   subsets: ["latin"],
//   weight: ["400", "500", "600", "700", "800", "900"],
//   style: ["normal", "italic"],
// });

// const libreBaskerville = Libre_Baskerville({
//   variable: "--font-libre-baskerville",
//   subsets: ["latin"],
//   weight: ["400", "700"],
//   style: ["normal", "italic"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} ${playfair.variable} ${libreBaskerville.variable} antialiased font-sans text-white`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

import "@/styles/globals.css";
import "@/styles/prosemirror.css";
// import "katex/dist/katex.min.css"; // Removed to avoid CSS ESM loader error

import Providers from "@/app/providers";
import { cal, inter } from "@/styles/fonts";

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.variable} ${cal.variable}`} suppressHydrationWarning>
      <body className="font-default">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}